version: "3.9"

services:
  clickhouse-db:
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: qwerty123
    ports:
      - "18123:8123"
      - "19000:9000"
